import { Resend } from "resend";
import { SUPPORT_EMAIL } from "@/lib/support";

export interface SendEmailParams {
  to: string | string[];
  subject: string;
  html: string;
  /** Plain text fallback. Auto-generated by Resend from html if omitted. */
  text?: string;
  from?: string;
  replyTo?: string | string[];
  /** Custom metadata for Resend dashboard (ASCII, max 256 chars each). */
  tags?: { name: string; value: string }[];
  /**
   * Unique per logical send — prevents duplicate emails on retries.
   * Pattern: `<event-type>/<entity-id>` (max 256 chars, expires after 24h).
   */
  idempotencyKey?: string;
}

export interface SendEmailResult {
  ok: boolean;
  id?: string;
  error?: string;
  skipped?: boolean;
}

let resendClient: Resend | null = null;

export function getResendClient(): Resend | null {
  const apiKey = process.env.RESEND_API_KEY?.trim();
  if (!apiKey) return null;
  if (!resendClient) {
    resendClient = new Resend(apiKey);
  }
  return resendClient;
}

export function hasResendKey(): boolean {
  return Boolean(process.env.RESEND_API_KEY?.trim());
}

/** Verified production sender — never use onboarding@resend.dev in production. */
export function getDefaultFromAddress(): string {
  const from = process.env.RESEND_FROM_EMAIL?.trim();
  if (from) return from;
  return "Quicksilver Algo <onboarding@quicksilveralgo.com>";
}

/** Support team mailbox for inbound + support replies. */
export function getSupportFromAddress(): string {
  const from = process.env.RESEND_SUPPORT_FROM?.trim();
  if (from) return from;
  return `Quicksilver Support <${SUPPORT_EMAIL}>`;
}

export function getDefaultReplyTo(): string {
  return process.env.RESEND_REPLY_TO?.trim() || SUPPORT_EMAIL;
}

/**
 * Send email via official Resend Node SDK.
 * Uses { data, error } response pattern — does not rely on thrown errors for API failures.
 */
export async function sendEmail(params: SendEmailParams): Promise<boolean> {
  const result = await sendEmailDetailed(params);
  return result.ok;
}

export async function sendEmailDetailed(
  params: SendEmailParams
): Promise<SendEmailResult> {
  const resend = getResendClient();
  if (!resend) {
    console.warn("[email] RESEND_API_KEY not set — skipping send");
    return { ok: false, skipped: true, error: "RESEND_API_KEY not configured" };
  }

  const to = Array.isArray(params.to) ? params.to : [params.to];
  if (to.length === 0 || to.some((addr) => !addr?.trim())) {
    return { ok: false, error: "Missing recipient" };
  }

  const payload = {
    from: params.from ?? getDefaultFromAddress(),
    to,
    subject: params.subject,
    html: params.html,
    ...(params.text ? { text: params.text } : {}),
    replyTo: params.replyTo ?? getDefaultReplyTo(),
    ...(params.tags?.length ? { tags: params.tags } : {}),
    ...(params.idempotencyKey
      ? { idempotencyKey: params.idempotencyKey.slice(0, 256) }
      : {}),
  };

  const { data, error } = await resend.emails.send(payload);

  if (error) {
    console.error("[email] Resend error:", error.message ?? error);
    return {
      ok: false,
      error: error.message ?? "Resend API error",
    };
  }

  if (!data?.id) {
    console.error("[email] Resend returned no id");
    return { ok: false, error: "Resend returned no message id" };
  }

  console.info(`[email] sent id=${data.id} to=${to.join(",")}`);
  return { ok: true, id: data.id };
}

/** Convert plain text body to safe HTML for bulk emails. */
export function plainTextToEmailHtml(text: string): string {
  const escaped = text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
  const withBreaks = escaped.replace(/\n/g, "<br />");
  return `<div style="font-family:ui-sans-serif,system-ui,sans-serif;color:#0f172a;line-height:1.6;font-size:15px;max-width:600px;">${withBreaks}</div>`;
}
